# Generated by Django 4.1.7 on 2023-11-21 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('POLYGON', 'Polygon')], max_length=255)),
                ('icon', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField()),
                ('gecko_id', models.CharField(default='', max_length=255)),
                ('gecko_chain_identifier', models.CharField(default='', max_length=255)),
                ('gecko_name', models.CharField(default='', max_length=255)),
                ('gecko_shortname', models.CharField(default='', max_length=255)),
                ('gecko_native_coin_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('logo_uri', models.CharField(default='', max_length=255)),
                ('decimals', models.IntegerField(default=0)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blockchain_contracts', to='app.blockchain')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Fiat',
                'verbose_name_plural': 'Fiats',
            },
        ),
        migrations.CreateModel(
            name='Polygon_ERC20_Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockNumber', models.CharField(max_length=255)),
                ('timeStamp', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('blockHash', models.CharField(max_length=255)),
                ('fromAddress', models.CharField(max_length=255)),
                ('toAddress', models.CharField(max_length=255)),
                ('contractAddress', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('tokenName', models.CharField(max_length=255)),
                ('tokenDecimal', models.CharField(max_length=255)),
                ('transactionIndex', models.CharField(max_length=255)),
                ('gas', models.CharField(max_length=255)),
                ('gasPrice', models.CharField(max_length=255)),
                ('gasUsed', models.CharField(max_length=255)),
                ('cumulativeGasUsed', models.CharField(max_length=255)),
                ('input', models.CharField(max_length=255)),
                ('confirmations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PolygonERC20',
                'verbose_name_plural': 'PolygonERC20',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_positions', to='app.contract')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell'), ('DEP', 'Deposit'), ('WTH', 'Withdrawal')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('running_quantity', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('buy_quantity', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('sell_quantity', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('price_contract_based', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_contract_based', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost_contract_based', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_cost_contract_based', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_gain_contract_based', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_gain_percentage_contract_based', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('date', models.DateTimeField(db_index=True)),
                ('comment', models.TextField(default='')),
                ('hash', models.CharField(db_index=True, default='', max_length=255)),
                ('against_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_transactions', to='app.contract')),
                ('against_fiat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_fiats', to='app.fiat')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_transactions', to='app.position')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_positions', to='app.wallet'),
        ),
    ]
