# Generated by Django 4.1.7 on 2023-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="price_contract_based",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
