# Generated by Django 4.1.7 on 2023-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
