# Generated by Django 4.1.7 on 2023-11-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_position_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='contract_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractlink_positions', to='app.contractlink'),
        ),
    ]
