# Generated by Django 4.1.7 on 2023-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_transaction_price_contract_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cost_contract_based",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
