# Generated by Django 4.2.7 on 2024-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contract_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
        ),
    ]
