# Generated by Django 4.1.7 on 2023-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_transaction_cost_contract_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="running_quantity",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=32),
        ),
    ]
