# Generated by Django 4.1.7 on 2023-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_transaction_running_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="purchase_quantity",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sell_quantity",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=32),
        ),
    ]
