# Generated by Django 4.2.7 on 2024-04-18 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wallet_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_process',
            name='delete_task',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='wallet_process',
            name='download_task',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='wallet_process',
            name='resync_task',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
