# Generated by Django 4.2.7 on 2024-04-30 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_wallet_process_delete_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(choices=[('POLYGON', 'Polygon'), ('BNB', 'BNB Chain'), ('METIS', 'Metis'), ('ARBITRUM', 'Arbitrum'), ('OPTIMISTIC', 'Optimistic')], max_length=255),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_positions_above_threshold', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserSetting',
                'verbose_name_plural': 'UserSettings',
            },
        ),
    ]
