# Generated by Django 4.1.7 on 2023-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transaction_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon_ERC20_Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockNumber', models.CharField(max_length=255)),
                ('timeStamp', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('blockHash', models.CharField(max_length=255)),
                ('fromAddress', models.CharField(max_length=255)),
                ('toAddress', models.CharField(max_length=255)),
                ('contractAddress', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('tokenName', models.CharField(max_length=255)),
                ('tokenDecimal', models.CharField(max_length=255)),
                ('transactionIndex', models.CharField(max_length=255)),
                ('gas', models.CharField(max_length=255)),
                ('gasPrice', models.CharField(max_length=255)),
                ('gasUsed', models.CharField(max_length=255)),
                ('cumulativeGasUsed', models.CharField(max_length=255)),
                ('input', models.CharField(max_length=255)),
                ('confirmations', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
