# Generated by Django 4.2.7 on 2024-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fiat_short_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_fiat_based',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
    ]
