# Generated by Django 4.1.7 on 2023-11-15 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_transaction_purchase_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="purchase_quantity",
            new_name="buy_quantity",
        ),
    ]
