# Generated by Django 4.2.7 on 2024-08-10 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaction_price_fiat_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprocess',
            name='delete_task_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='download_task_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='resync_task_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
