# Generated by Django 4.1.7 on 2023-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_purchase_quantity_transaction_buy_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="avg_cost_contract_based",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_cost_contract_based",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
