# Generated by Django 4.2.7 on 2024-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blockchain_name_usersetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet_Process',
            new_name='WalletProcess',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_cost_contract_based',
        ),
        migrations.AddField(
            model_name='position',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='position',
            name='capital_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='position',
            name='total_buy_quantity',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='position',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_gain_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
