# Generated by Django 4.2.7 on 2024-05-16 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_wallet_process_walletprocess_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'verbose_name': 'Blockchain', 'verbose_name_plural': 'Blockchains'},
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='cost_contract_based',
            new_name='total_cost_contract_based',
        ),
        migrations.RemoveField(
            model_name='fiat',
            name='code',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='position',
            name='total_buy_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='avg_cost_contract_based',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='capital_gain_contract_based',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='capital_gain_percentage_contract_based',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cost',
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_day_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_month',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_month_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_week',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_week_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiat',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiat',
            name='symbol',
            field=models.CharField(default='USD', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_fiat_based',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_cost_fiat_based',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('BNB Chain', 'BNB Chain'), ('Metis', 'Metis'), ('Arbitrum', 'Arbitrum'), ('Optimistic', 'Optimistic')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.blockchain'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fiat',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.contract'),
        ),
        migrations.AlterField(
            model_name='position',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.position'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['symbol'], name='app_contrac_symbol_c1e2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['wallet', 'contract'], name='app_positio_wallet__6b3077_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['position'], name='app_transac_positio_0c891e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'address'], name='app_wallet_user_id_4c1cad_idx'),
        ),
    ]
