# Generated by Django 4.2.7 on 2024-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blockchain_options_alter_usersetting_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='app_contrac_symbol_c1e2e6_idx',
        ),
        migrations.AlterField(
            model_name='contract',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['name', 'symbol'], name='app_contrac_name_b5e74e_idx'),
        ),
    ]
