# Generated by Django 4.2.7 on 2024-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_arbitrum_erc20_raw_bsc_bep20_raw_optimism_erc20_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbitrum_ERC20_Raw',
        ),
        migrations.DeleteModel(
            name='BSC_BEP20_Raw',
        ),
        migrations.DeleteModel(
            name='Optimism_ERC20_Raw',
        ),
        migrations.DeleteModel(
            name='Polygon_ERC20_Raw',
        ),
    ]
