# Generated by Django 4.2.7 on 2024-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_arbitrum_erc20_raw_delete_bsc_bep20_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_contract_based',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
    ]
