# Generated by Django 4.2.7 on 2024-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('BSC', 'BSC'), ('Metis', 'Metis'), ('Arbitrum', 'Arbitrum'), ('Optimistic', 'Optimistic')], max_length=255, unique=True),
        ),
    ]
