# Generated by Django 4.2.7 on 2024-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_blockchain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('BSC', 'BSC'), ('Metis', 'Metis'), ('Arbitrum', 'Arbitrum'), ('Optimism', 'Optimism')], max_length=255, unique=True),
        ),
    ]
