# Generated by Django 4.2.7 on 2024-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contract_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='show_only_secure_contracts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('fee', 'Fee'), ('suspicious', 'Suspicious'), ('collateral', 'Collateral')], default='standard', max_length=20),
        ),
    ]
