# Generated by Django 4.2.7 on 2024-06-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usersetting_show_only_secure_contracts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='amount',
        ),
    ]
