# Generated by Django 4.2.7 on 2024-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_position_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('time', models.DateTimeField(db_index=True)),
                ('high', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('open', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('volume_from', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('volume_to', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'indexes': [models.Index(fields=['symbol', 'reference', 'time'], name='app_marketd_symbol_09b653_idx')],
            },
        ),
    ]
