const products = [
    {
      id: "1",
      name: "Wallet 1",
      address: "0x040b5f7de5b22a7a409bfa…",
      description: "description gdsfs 1",
      amount: "4,881.54",
      realized: "$412.92",
      realized_color: "success.main",
      unrealized: "$772.92",
      unrealized_color: "success.main",
    },
    {
      id: "2",
      name: "Wallet 2",
      address: "0x040b5f7de5b22a7a409bfa…",
      description: "description gdsfs 2",
      amount: "24.5",
      realized: "$4,012.92",
      realized_color: "success.main",
      unrealized: "$112.92",
      unrealized_color: "success.main",
    },
    {
      id: "3",
      name: "Wallet 3",
      address: "0x040b5f7de5b22a7a409bfa…",
      description: "description gdsfs 3",
      amount: "12.8",
      realized: "$-1,012.92",
      realized_color: "error.main",
      unrealized: "$-512.92",
      unrealized_color: "error.main",
    },
    {
      id: "4",
      name: "Wallet 4",
      address: "0x040b5f7de5b22a7a409bfa…",
      description: "description gdsfs 4",
      amount: "2.4",
      realized: "$-912.92",
      realized_color: "error.main",
      unrealized: "$-62.92",
      unrealized_color: "error.main",
    },
  ];

  const positions = [
    {
      img: "/images/users/1.jpg",
      title: "Bitcoin",
      subtext: "0.0234 BTC",
      status: "primary.main",
      percentage: "77.65%",
      amount: "$ 3,790.61",
    },
    {
      img: "/images/users/2.jpg",
      title: "Ethereum",
      subtext: "0.536 ETH",
      status: "secondary.main",
      percentage: "45.65%",
      amount: "$ 2,790.61",
    },
    {
      img: "/images/users/3.jpg",
      title: "Injective Protocol",
      subtext: "10.797 INJ",
      status: "error.main",
      percentage: "11.65%",
      amount: "$ 1,790.61",
    },
    {
      img: "/images/users/4.jpg",
      title: "Lido DAO Token",
      subtext: "103.326 LDO",
      status: "warning.main",
      percentage: "5.65%",
      amount: "$ 790.61",
    },
    {
      img: "/images/users/5.jpg",
      title: "USD Coin (PoS)",
      subtext: "3,786.828 USDC.e",
      status: "warning.main",
      percentage: "2.65%",
      amount: "$ 790.61",
    },
  ];