# Generated by Django 4.1.7 on 2023-11-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('POLYGON', 'Polygon')], max_length=255)),
                ('icon', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField()),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('logo_uri', models.CharField(default='', max_length=255)),
                ('decimals', models.IntegerField(default=0)),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blockchain_contracts', to='poc.blockchain')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
                ('contract_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractlink_positions', to='poc.contract')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell'), ('DEP', 'Deposit'), ('WTH', 'Withdrawal')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateTimeField(db_index=True)),
                ('comment', models.TextField(default='')),
                ('hash', models.CharField(db_index=True, default='', max_length=255)),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_transactions', to='poc.position')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='ContractLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('sys_creation_date', models.DateTimeField(auto_now_add=True)),
                ('sys_update_date', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_contractlinks', to='poc.contract')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_contractlinks', to='poc.wallet')),
            ],
            options={
                'verbose_name': 'ContractLink',
                'verbose_name_plural': 'ContractLinks',
            },
        ),
    ]
