# Generated by Django 4.1.7 on 2023-11-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='sys_creation_date',
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='sys_update_date',
        ),
    ]
