# Generated by Django 4.2.7 on 2024-11-02 08:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprocess',
            name='delete_task_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='full_download_task',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='full_download_task_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='full_download_task_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
