# Generated by Django 4.2.7 on 2024-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('increase', 'Increase'), ('diminution', 'Diminution'), ('close', 'Close')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='contract',
            name='logo_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='relative_symbol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
