# Generated by Django 4.2.7 on 2024-12-17 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_status_transaction_status_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.contract')),
                ('download_task', models.UUIDField(default=uuid.uuid4)),
                ('download_task_date', models.DateTimeField(default=datetime.datetime.now)),
                ('download_task_status', models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20)),
            ],
            options={
                'verbose_name': 'Contract Process',
                'verbose_name_plural': 'Contracts Processes',
            },
        ),
    ]
