# Generated by Django 4.2.7 on 2024-07-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blockchain_transaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
