# Generated by Django 4.2.7 on 2024-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contract_description_contract_market_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('BSC', 'BSC'), ('Metis', 'Metis'), ('Arbitrum', 'Arbitrum'), ('Optimism', 'Optimism'), ('Base', 'Base')], max_length=255, unique=True),
        ),
    ]
