# Generated by Django 4.2.7 on 2024-08-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contract_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiat',
            name='short_symbol',
            field=models.CharField(default='', max_length=3),
        ),
    ]
