# Generated by Django 4.2.7 on 2025-06-12 08:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transaction_running_capital_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processes', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resync_task', models.UUIDField(default=uuid.uuid4)),
                ('resync_task_date', models.DateTimeField(default=datetime.datetime.now)),
                ('resync_task_status', models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20)),
            ],
            options={
                'verbose_name': 'User Process',
                'verbose_name_plural': 'Users Processes',
            },
        ),
    ]
