# Generated by Django 4.2.7 on 2024-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_walletprocess_delete_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprocess',
            name='download_task_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='walletprocess',
            name='resync_task_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
