# Generated by Django 4.2.7 on 2025-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
