# Generated by Django 4.2.7 on 2024-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_walletprocess_download_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='relative_symbol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
